# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CVD.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.open_button = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.open_button.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.open_button.setObjectName("open_button")
        self.horizontalLayout_2.addWidget(self.open_button)
        self.save_button = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.save_button.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_time_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_time_1.setObjectName("lineEdit_time_1")
        self.verticalLayout.addWidget(self.lineEdit_time_1)
        self.lineEdit_time_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_time_2.setObjectName("lineEdit_time_2")
        self.verticalLayout.addWidget(self.lineEdit_time_2)
        self.lineEdit_time_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_time_3.setObjectName("lineEdit_time_3")
        self.verticalLayout.addWidget(self.lineEdit_time_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_temp_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_temp_1.setObjectName("lineEdit_temp_1")
        self.verticalLayout_2.addWidget(self.lineEdit_temp_1)
        self.lineEdit_temp_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_temp_2.setObjectName("lineEdit_temp_2")
        self.verticalLayout_2.addWidget(self.lineEdit_temp_2)
        self.lineEdit_temp_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_temp_3.setObjectName("lineEdit_temp_3")
        self.verticalLayout_2.addWidget(self.lineEdit_temp_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_gas_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_gas_1.setObjectName("label_gas_1")
        self.verticalLayout_3.addWidget(self.label_gas_1)
        self.lineEdit_heFlow_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_heFlow_1.setObjectName("lineEdit_heFlow_1")
        self.verticalLayout_3.addWidget(self.lineEdit_heFlow_1)
        self.lineEdit_heFlow_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_heFlow_2.setObjectName("lineEdit_heFlow_2")
        self.verticalLayout_3.addWidget(self.lineEdit_heFlow_2)
        self.lineEdit_heFlow_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_heFlow_3.setObjectName("lineEdit_heFlow_3")
        self.verticalLayout_3.addWidget(self.lineEdit_heFlow_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_gas_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_gas_2.setObjectName("label_gas_2")
        self.verticalLayout_4.addWidget(self.label_gas_2)
        self.lineEdit_h2Flow_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_h2Flow_1.setObjectName("lineEdit_h2Flow_1")
        self.verticalLayout_4.addWidget(self.lineEdit_h2Flow_1)
        self.lineEdit_h2Flow_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_h2Flow_2.setObjectName("lineEdit_h2Flow_2")
        self.verticalLayout_4.addWidget(self.lineEdit_h2Flow_2)
        self.lineEdit_h2Flow_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_h2Flow_3.setObjectName("lineEdit_h2Flow_3")
        self.verticalLayout_4.addWidget(self.lineEdit_h2Flow_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_gas_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_gas_3.setObjectName("label_gas_3")
        self.verticalLayout_5.addWidget(self.label_gas_3)
        self.lineEdit_c2h4Flow_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_c2h4Flow_1.setObjectName("lineEdit_c2h4Flow_1")
        self.verticalLayout_5.addWidget(self.lineEdit_c2h4Flow_1)
        self.lineEdit_c2h4Flow_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_c2h4Flow_2.setObjectName("lineEdit_c2h4Flow_2")
        self.verticalLayout_5.addWidget(self.lineEdit_c2h4Flow_2)
        self.lineEdit_c2h4Flow_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_c2h4Flow_3.setObjectName("lineEdit_c2h4Flow_3")
        self.verticalLayout_5.addWidget(self.lineEdit_c2h4Flow_3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.label_author = QtWidgets.QLabel(self.centralwidget)
        self.label_author.setObjectName("label_author")
        self.verticalLayout_7.addWidget(self.label_author)
        self.label_creation_date = QtWidgets.QLabel(self.centralwidget)
        self.label_creation_date.setObjectName("label_creation_date")
        self.verticalLayout_7.addWidget(self.label_creation_date)
        self.label_last_updated = QtWidgets.QLabel(self.centralwidget)
        self.label_last_updated.setObjectName("label_last_updated")
        self.verticalLayout_7.addWidget(self.label_last_updated)
        self.label_notes = QtWidgets.QLabel(self.centralwidget)
        self.label_notes.setObjectName("label_notes")
        self.verticalLayout_7.addWidget(self.label_notes)
        self.gridLayout.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 395, 22))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Setpoints</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Step No."))
        self.label_6.setText(_translate("MainWindow", "Step 1"))
        self.label_8.setText(_translate("MainWindow", "Step 2"))
        self.label_9.setText(_translate("MainWindow", "Step 3"))
        self.label.setText(_translate("MainWindow", "Time"))
        self.label_5.setText(_translate("MainWindow", "Temp"))
        self.label_gas_1.setText(_translate("MainWindow", "Gas 1"))
        self.label_gas_2.setText(_translate("MainWindow", "<html><head/><body><p>Gas 2</p></body></html>"))
        self.label_gas_3.setText(_translate("MainWindow", "<html><head/><body><p>Gas 3</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Recipe Meta Data</span></p></body></html>"))
        self.label_author.setText(_translate("MainWindow", "Author: N/A"))
        self.label_creation_date.setText(_translate("MainWindow", "Creation Date: N/A"))
        self.label_last_updated.setText(_translate("MainWindow", "Last Updated: N/A"))
        self.label_notes.setText(_translate("MainWindow", "Notes:"))
