# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CVD.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 748)
        MainWindow.setMinimumSize(QtCore.QSize(932, 748))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(521, 9, 402, 608))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gas_graph = PlotWidget(self.layoutWidget)
        self.gas_graph.setMinimumSize(QtCore.QSize(400, 300))
        self.gas_graph.setObjectName("gas_graph")
        self.verticalLayout_8.addWidget(self.gas_graph)
        self.temp_graph = PlotWidget(self.layoutWidget)
        self.temp_graph.setMinimumSize(QtCore.QSize(400, 300))
        self.temp_graph.setObjectName("temp_graph")
        self.verticalLayout_8.addWidget(self.temp_graph)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 460, 351, 113))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.label_author = QtWidgets.QLabel(self.layoutWidget1)
        self.label_author.setObjectName("label_author")
        self.verticalLayout_7.addWidget(self.label_author)
        self.label_creation_date = QtWidgets.QLabel(self.layoutWidget1)
        self.label_creation_date.setObjectName("label_creation_date")
        self.verticalLayout_7.addWidget(self.label_creation_date)
        self.label_last_updated = QtWidgets.QLabel(self.layoutWidget1)
        self.label_last_updated.setObjectName("label_last_updated")
        self.verticalLayout_7.addWidget(self.label_last_updated)
        self.label_notes = QtWidgets.QLabel(self.layoutWidget1)
        self.label_notes.setObjectName("label_notes")
        self.verticalLayout_7.addWidget(self.label_notes)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 260, 501, 34))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.open_button = QtWidgets.QDialogButtonBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_button.sizePolicy().hasHeightForWidth())
        self.open_button.setSizePolicy(sizePolicy)
        self.open_button.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.open_button.setObjectName("open_button")
        self.horizontalLayout_2.addWidget(self.open_button)
        self.save_button = QtWidgets.QDialogButtonBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 330, 504, 121))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget3)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_time_1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_time_1.setObjectName("lineEdit_time_1")
        self.verticalLayout.addWidget(self.lineEdit_time_1)
        self.lineEdit_time_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_time_2.setObjectName("lineEdit_time_2")
        self.verticalLayout.addWidget(self.lineEdit_time_2)
        self.lineEdit_time_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_time_3.setObjectName("lineEdit_time_3")
        self.verticalLayout.addWidget(self.lineEdit_time_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_temp_1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_temp_1.setObjectName("lineEdit_temp_1")
        self.verticalLayout_2.addWidget(self.lineEdit_temp_1)
        self.lineEdit_temp_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_temp_2.setObjectName("lineEdit_temp_2")
        self.verticalLayout_2.addWidget(self.lineEdit_temp_2)
        self.lineEdit_temp_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_temp_3.setObjectName("lineEdit_temp_3")
        self.verticalLayout_2.addWidget(self.lineEdit_temp_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_gas_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_gas_1.setObjectName("label_gas_1")
        self.verticalLayout_3.addWidget(self.label_gas_1)
        self.lineEdit_heFlow_1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_heFlow_1.setObjectName("lineEdit_heFlow_1")
        self.verticalLayout_3.addWidget(self.lineEdit_heFlow_1)
        self.lineEdit_heFlow_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_heFlow_2.setObjectName("lineEdit_heFlow_2")
        self.verticalLayout_3.addWidget(self.lineEdit_heFlow_2)
        self.lineEdit_heFlow_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_heFlow_3.setObjectName("lineEdit_heFlow_3")
        self.verticalLayout_3.addWidget(self.lineEdit_heFlow_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_gas_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_gas_2.setObjectName("label_gas_2")
        self.verticalLayout_4.addWidget(self.label_gas_2)
        self.lineEdit_h2Flow_1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_h2Flow_1.setObjectName("lineEdit_h2Flow_1")
        self.verticalLayout_4.addWidget(self.lineEdit_h2Flow_1)
        self.lineEdit_h2Flow_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_h2Flow_2.setObjectName("lineEdit_h2Flow_2")
        self.verticalLayout_4.addWidget(self.lineEdit_h2Flow_2)
        self.lineEdit_h2Flow_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_h2Flow_3.setObjectName("lineEdit_h2Flow_3")
        self.verticalLayout_4.addWidget(self.lineEdit_h2Flow_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_gas_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_gas_3.setObjectName("label_gas_3")
        self.verticalLayout_5.addWidget(self.label_gas_3)
        self.lineEdit_c2h4Flow_1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_c2h4Flow_1.setObjectName("lineEdit_c2h4Flow_1")
        self.verticalLayout_5.addWidget(self.lineEdit_c2h4Flow_1)
        self.lineEdit_c2h4Flow_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_c2h4Flow_2.setObjectName("lineEdit_c2h4Flow_2")
        self.verticalLayout_5.addWidget(self.lineEdit_c2h4Flow_2)
        self.lineEdit_c2h4Flow_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_c2h4Flow_3.setObjectName("lineEdit_c2h4Flow_3")
        self.verticalLayout_5.addWidget(self.lineEdit_c2h4Flow_3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 170, 111, 32))
        self.label_12.setObjectName("label_12")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 580, 501, 101))
        self.textEdit.setObjectName("textEdit")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 221, 32))
        self.label_13.setObjectName("label_13")
        self.button_apply_setpoints = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.button_apply_setpoints.setGeometry(QtCore.QRect(200, 40, 81, 25))
        self.button_apply_setpoints.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.button_apply_setpoints.setObjectName("button_apply_setpoints")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 200, 191, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_author_2 = QtWidgets.QLabel(self.widget)
        self.label_author_2.setObjectName("label_author_2")
        self.horizontalLayout_3.addWidget(self.label_author_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label_author_3 = QtWidgets.QLabel(self.widget)
        self.label_author_3.setObjectName("label_author_3")
        self.horizontalLayout_3.addWidget(self.label_author_3)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 230, 383, 27))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(11, 300, 362, 27))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_start_recipe = QtWidgets.QPushButton(self.widget2)
        self.button_start_recipe.setObjectName("button_start_recipe")
        self.horizontalLayout_4.addWidget(self.button_start_recipe)
        self.button_stop_recipe = QtWidgets.QPushButton(self.widget2)
        self.button_stop_recipe.setObjectName("button_stop_recipe")
        self.horizontalLayout_4.addWidget(self.button_stop_recipe)
        self.label_recipe_status = QtWidgets.QLabel(self.widget2)
        self.label_recipe_status.setObjectName("label_recipe_status")
        self.horizontalLayout_4.addWidget(self.label_recipe_status)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(10, 40, 171, 128))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.widget3)
        self.label_14.setMinimumSize(QtCore.QSize(51, 0))
        self.label_14.setMaximumSize(QtCore.QSize(51, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(51, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(51, 16777215))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.widget3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_gas_4 = QtWidgets.QLabel(self.widget3)
        self.label_gas_4.setMinimumSize(QtCore.QSize(51, 0))
        self.label_gas_4.setMaximumSize(QtCore.QSize(51, 16777215))
        self.label_gas_4.setObjectName("label_gas_4")
        self.horizontalLayout_7.addWidget(self.label_gas_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(51, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(51, 16777215))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.label_15 = QtWidgets.QLabel(self.widget3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_gas_5 = QtWidgets.QLabel(self.widget3)
        self.label_gas_5.setMinimumSize(QtCore.QSize(51, 0))
        self.label_gas_5.setMaximumSize(QtCore.QSize(51, 16777215))
        self.label_gas_5.setObjectName("label_gas_5")
        self.horizontalLayout_8.addWidget(self.label_gas_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(51, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(51, 16777215))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.label_16 = QtWidgets.QLabel(self.widget3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_gas_6 = QtWidgets.QLabel(self.widget3)
        self.label_gas_6.setMinimumSize(QtCore.QSize(51, 0))
        self.label_gas_6.setMaximumSize(QtCore.QSize(51, 16777215))
        self.label_gas_6.setObjectName("label_gas_6")
        self.horizontalLayout_9.addWidget(self.label_gas_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(51, 0))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(51, 16777215))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_9.addWidget(self.lineEdit_5)
        self.label_17 = QtWidgets.QLabel(self.widget3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.widget4 = QtWidgets.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(290, 40, 131, 111))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.widget4)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_10.addWidget(self.label_18)
        self.label_temp_setpoint = QtWidgets.QLabel(self.widget4)
        self.label_temp_setpoint.setObjectName("label_temp_setpoint")
        self.verticalLayout_10.addWidget(self.label_temp_setpoint)
        self.label_gas_1_setpoint = QtWidgets.QLabel(self.widget4)
        self.label_gas_1_setpoint.setObjectName("label_gas_1_setpoint")
        self.verticalLayout_10.addWidget(self.label_gas_1_setpoint)
        self.label_gas_2_setpoint = QtWidgets.QLabel(self.widget4)
        self.label_gas_2_setpoint.setObjectName("label_gas_2_setpoint")
        self.verticalLayout_10.addWidget(self.label_gas_2_setpoint)
        self.label_gas_3_setpoint = QtWidgets.QLabel(self.widget4)
        self.label_gas_3_setpoint.setObjectName("label_gas_3_setpoint")
        self.verticalLayout_10.addWidget(self.label_gas_3_setpoint)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 22))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Recipe Meta Data</span></p></body></html>"))
        self.label_author.setText(_translate("MainWindow", "Author: N/A"))
        self.label_creation_date.setText(_translate("MainWindow", "Creation Date: N/A"))
        self.label_last_updated.setText(_translate("MainWindow", "Last Updated: N/A"))
        self.label_notes.setText(_translate("MainWindow", "Notes:"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Recipe</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Step No."))
        self.label_6.setText(_translate("MainWindow", "Step 1"))
        self.label_8.setText(_translate("MainWindow", "Step 2"))
        self.label_9.setText(_translate("MainWindow", "Step 3"))
        self.label.setText(_translate("MainWindow", "Time"))
        self.label_5.setText(_translate("MainWindow", "Temp."))
        self.label_gas_1.setText(_translate("MainWindow", "Gas 1"))
        self.label_gas_2.setText(_translate("MainWindow", "<html><head/><body><p>Gas 2</p></body></html>"))
        self.label_gas_3.setText(_translate("MainWindow", "<html><head/><body><p>Gas 3</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Logging</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Manual Controls</span></p></body></html>"))
        self.label_author_2.setText(_translate("MainWindow", "Sampling rate:"))
        self.label_author_3.setText(_translate("MainWindow", "Hz"))
        self.pushButton_3.setText(_translate("MainWindow", "Select File"))
        self.label_2.setText(_translate("MainWindow", "~/usr/Documents/CVD Data/2020-12-16.txt"))
        self.button_start_recipe.setText(_translate("MainWindow", "Start Recipe"))
        self.button_stop_recipe.setText(_translate("MainWindow", "Stop Recipe"))
        self.label_recipe_status.setText(_translate("MainWindow", "<html><head/><body><p>Recipe Status: <span style=\" font-weight:600;\">STOPPED</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Temp.:"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:super;\">o</span>C</p></body></html>"))
        self.label_gas_4.setText(_translate("MainWindow", "Gas 1:"))
        self.label_15.setText(_translate("MainWindow", "sccm"))
        self.label_gas_5.setText(_translate("MainWindow", "<html><head/><body><p>Gas 2:</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "sccm"))
        self.label_gas_6.setText(_translate("MainWindow", "<html><head/><body><p>Gas 3:</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "sccm"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Current Setpoints</span></p></body></html>"))
        self.label_temp_setpoint.setText(_translate("MainWindow", "<html><head/><body><p>Temp.: 0 <span style=\" vertical-align:super;\">o</span>C</p></body></html>"))
        self.label_gas_1_setpoint.setText(_translate("MainWindow", "Gas 1: 0 sccm"))
        self.label_gas_2_setpoint.setText(_translate("MainWindow", "Gas 2: 0 sccm"))
        self.label_gas_3_setpoint.setText(_translate("MainWindow", "Gas 3: 0 sccm"))
from pyqtgraph import PlotWidget
